// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package dhcpredirect

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dhcpRedirectDhcpConfig struct {
	_           structs.HostLayout
	HostIp      uint32
	PodIfindex  uint32
	PhysIfindex uint32
	PhysMac     [6]uint8
	Flags       uint16
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	dhcpRedirectMapConfigMap       = "config_map"
	dhcpRedirectMapStatsMap        = "stats_map"
	dhcpRedirectProgRedirectToPod  = "redirect_to_pod"
	dhcpRedirectProgRedirectToWire = "redirect_to_wire"
)

// loadDhcpRedirect returns the embedded CollectionSpec for dhcpRedirect.
func loadDhcpRedirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DhcpRedirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dhcpRedirect: %w", err)
	}

	return spec, err
}

// loadDhcpRedirectObjects loads dhcpRedirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dhcpRedirectObjects
//	*dhcpRedirectPrograms
//	*dhcpRedirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDhcpRedirectObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadDhcpRedirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dhcpRedirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dhcpRedirectSpecs struct {
	dhcpRedirectProgramSpecs
	dhcpRedirectMapSpecs
	dhcpRedirectVariableSpecs
}

// dhcpRedirectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dhcpRedirectProgramSpecs struct {
	RedirectToPod  *ebpf.ProgramSpec `ebpf:"redirect_to_pod"`
	RedirectToWire *ebpf.ProgramSpec `ebpf:"redirect_to_wire"`
}

// dhcpRedirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dhcpRedirectMapSpecs struct {
	ConfigMap *ebpf.MapSpec `ebpf:"config_map"`
	StatsMap  *ebpf.MapSpec `ebpf:"stats_map"`
}

// dhcpRedirectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dhcpRedirectVariableSpecs struct {
}

// dhcpRedirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDhcpRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type dhcpRedirectObjects struct {
	dhcpRedirectPrograms
	dhcpRedirectMaps
	dhcpRedirectVariables
}

func (o *dhcpRedirectObjects) Close() error {
	return _DhcpRedirectClose(
		&o.dhcpRedirectPrograms,
		&o.dhcpRedirectMaps,
	)
}

// dhcpRedirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDhcpRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type dhcpRedirectMaps struct {
	ConfigMap *ebpf.Map `ebpf:"config_map"`
	StatsMap  *ebpf.Map `ebpf:"stats_map"`
}

func (m *dhcpRedirectMaps) Close() error {
	return _DhcpRedirectClose(
		m.ConfigMap,
		m.StatsMap,
	)
}

// dhcpRedirectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDhcpRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type dhcpRedirectVariables struct {
}

// dhcpRedirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDhcpRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type dhcpRedirectPrograms struct {
	RedirectToPod  *ebpf.Program `ebpf:"redirect_to_pod"`
	RedirectToWire *ebpf.Program `ebpf:"redirect_to_wire"`
}

func (p *dhcpRedirectPrograms) Close() error {
	return _DhcpRedirectClose(
		p.RedirectToPod,
		p.RedirectToWire,
	)
}

func _DhcpRedirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dhcpredirect_bpfeb.o
var _DhcpRedirectBytes []byte
